# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-06 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs', '0006_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('comparator', models.CharField(choices=[('__lt__', '<'), ('__lte__', '<='), ('__gt__', '>'), ('__gte__', '>=')], default='__lt__', max_length=6, verbose_name='Comparator')),
                ('color', models.CharField(choices=[('default', 'Default'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='danger', max_length=20, verbose_name='Color')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('action', models.TextField(blank=True, null=True, verbose_name='Action')),
                ('period', models.TextField(blank=True, null=True, verbose_name='Period')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('months', models.ManyToManyField(to='configs.Month', verbose_name='Monitor Months')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.AbstractProduct', verbose_name='Product')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs.Type', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Monitor Profile',
                'verbose_name_plural': 'Monitor Profile',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('watch_all', models.BooleanField(default=False, verbose_name='Watch All')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Parent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.AbstractProduct', verbose_name='Product')),
                ('sources', models.ManyToManyField(to='configs.Source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Watchlist Item',
                'verbose_name_plural': 'Watchlist Items',
            },
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Watchlist'),
        ),
    ]
