# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-02 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0004_auto_20180919_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorprofile',
            name='row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Row'),
        ),
    ]
