# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-04-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0005_monitorprofile_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorprofile',
            name='always_display',
            field=models.BooleanField(default=False, verbose_name='Always Display'),
        ),
    ]
