# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import apps.posts.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.posts.utils.upload_location, verbose_name='File')),
                ('content', models.TextField(verbose_name='Content')),
                ('publish', models.DateField(default=django.utils.timezone.now, verbose_name='Publish')),
                ('read_time', models.IntegerField(default=0, verbose_name='Read Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
