# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 05:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_price', models.FloatField(blank=True, null=True, verbose_name='Up Price')),
                ('mid_price', models.FloatField(blank=True, null=True, verbose_name='Mid Price')),
                ('low_price', models.FloatField(blank=True, null=True, verbose_name='Low Pirce')),
                ('avg_price', models.FloatField(verbose_name='Average Price')),
                ('avg_weight', models.FloatField(blank=True, null=True, verbose_name='Average Weight')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Volume')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.AbstractProduct', verbose_name='Product')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.Source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Daily Transition',
                'verbose_name_plural': 'Daily Transitions',
            },
        ),
    ]
