# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytran',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.Source', verbose_name='Source'),
        ),
    ]
