# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-12 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrans', '0002_auto_20180926_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytran',
            name='not_updated',
            field=models.IntegerField(default=0, verbose_name='Not Updated Count'),
        ),
    ]
