# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-27 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_db_logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('statuslog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_db_logger.StatusLog')),
            ],
            options={
                'verbose_name_plural': 'Logs',
                'verbose_name': 'Log',
            },
            bases=('django_db_logger.statuslog',),
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name_plural': 'LogTypes',
                'verbose_name': 'LogType',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.LogType', verbose_name='Log Type'),
        ),
    ]
