services: docker

before_install:
  # Prepare environs file
  - sudo cp .env.example .env
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
install:
  # Start the docker stuff
  - docker-compose up -d
  - sleep 10
script:
  # Code styles
  - docker-compose exec web flake8 --exclude=migrations --ignore=E123,E133,E226,E241,E242,E402,E501,F401,F403,F405,W503 ./
  # Run tests
  - docker-compose exec web pytest -m "not secret"
  # Show logs
  - docker-compose logs --tail=30 web