language: python
python:
  - "3.6"
services:
  - postgresql
env:
  global:
    DJANGO_SETTINGS_MODULE=dashboard.settings.travis
  matrix:
    - DJANGO=1.9 DB=postgres
install:
  - pip install -q Django==$DJANGO
  - pip install pycodestyle
  - pip install flake8
  - pip install -q -r src/requirements.txt
before_script:
  - "pycodestyle --exclude=migrations --ignore=E123,E133,E226,E241,E242,E402,E501,W503 ./src"
  - "flake8 --exclude=migrations --ignore=E123,E133,E226,E241,E242,E402,E501,F401,F403,F405,W503 ./src"
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - cd src/
  - export SECRET_KEY=$SECRET_KEY
  - export AMIS_URL=$AMIS_URL
  - export APIS_URL=$APIS_URL
  - export EFISH_URL=$EFISH_URL
  - python manage.py migrate
  - python manage.py loaddata logs accounts configs sources
  - python manage.py loaddata cog01 cog02 cog03 cog04 cog05 cog06 cog07 cog08 cog09 cog10 cog11 cog12 cog13
  - python manage.py test dailytrans
  - python manage.py test chickens cattles ducks gooses rams hogs rices
  - python manage.py test crops.tests.test_builder fruits.tests.test_builder flowers.tests.test_builder