version: '3.4'

volumes:
    postgres_data: {}

services:
  postgres:
    container_name: db
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: ${REDIS_HOST}
    image: redis:4.0

  web: &web
    container_name: web
    image: aprp-web
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ./src:/app
    command: /app/scripts/start.sh
    entrypoint: /app/scripts/entrypoint.sh
    restart: on-failure
    ports:
      - "8000:8000"
    env_file: .env

  worker:
    <<: *web
    container_name: worker
    depends_on:
      - web
    ports: []
    command: ["celery", "worker", "--app=dashboard", "--pool=eventlet", "--loglevel=info"]
    entrypoint: ./scripts/entrypoint.sh

  beat:
    <<: *web
    container_name: beat
    depends_on:
      - web
    ports: []
    command: ["celery", "worker", "--app=dashboard", "--loglevel=info"]
    entrypoint: ./scripts/entrypoint.sh
