version: '3.3'

volumes:
    postgres_data: {}

services:
  web:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ./src:/app
    command: /app/scripts/start.sh
    entrypoint: /app/scripts/entrypoint.sh
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=dashboard.settings.local

  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
