# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-05 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_abstractproduct_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='ajax',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='static',
        ),
    ]
