# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-01 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_auto_20180913_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='display_on_config',
            field=models.BooleanField(default=True, verbose_name='Display On Config'),
        ),
    ]
