# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-20 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='order',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
    ]
