# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-06 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorprofile',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configs.AbstractProduct', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitorprofile',
            name='watchlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Watchlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='end_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Start Date'),
        ),
    ]
