# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-26 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0002_auto_20180720_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watch_all',
            field=models.BooleanField(default=False, verbose_name='Watch All'),
        ),
    ]
