# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0002_auto_20180906_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorprofile',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Monitor Info'),
        ),
    ]
