# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-26 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0003_watchlist_watch_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistitem',
            name='price',
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='low_control_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Low Control Price'),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='monitor_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Monitor Price'),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='up_control_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Up Control Price'),
        ),
    ]
