# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-31 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0004_auto_20180726_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistitem',
            name='monitor_price',
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='low_monitor_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Low Monitor Price'),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='up_monitor_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Up Monitor Price'),
        ),
    ]
