# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-31 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0005_auto_20180731_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('comparison', models.CharField(choices=[('__lt__', 'Less Than'), ('__lte__', 'Less Than Equal'), ('__gt__', 'Greater Than'), ('__gte__', 'Greater Than Equal')], default='__lt__', max_length=6, verbose_name='Comparison')),
                ('color', models.CharField(choices=[('#A90329', 'Danger'), ('#C79121', 'Alert'), ('#92A2A8', 'Info'), ('#71843F', 'Success'), ('#3276B1', 'Primary'), ('#999999', 'Default')], default='#999999', max_length=7)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Actions')),
                ('actions', models.TextField(blank=True, null=True, verbose_name='Actions')),
            ],
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'Watchlist', 'verbose_name_plural': 'Watchlists'},
        ),
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'verbose_name': 'Watchlist Item', 'verbose_name_plural': 'Watchlist Items'},
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='low_control_price',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='low_monitor_price',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='up_control_price',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='up_monitor_price',
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlists.WatchlistItem', verbose_name='Watchlist Item'),
        ),
    ]
