# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-31 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0006_auto_20180731_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorprofile',
            name='color',
            field=models.CharField(choices=[('#A90329', 'Danger'), ('#C79121', 'Alert'), ('#92A2A8', 'Info'), ('#71843F', 'Success'), ('#3276B1', 'Primary'), ('#999999', 'Default')], default='#999999', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='monitorprofile',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='monitorprofile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlists.WatchlistItem', verbose_name='Watchlist Item'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Parent'),
        ),
    ]
