# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-31 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0007_auto_20180731_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='months',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='Monitor Months'),
        ),
        migrations.AlterField(
            model_name='monitorprofile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlists.WatchlistItem', verbose_name='Watchlist Item'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Parent'),
        ),
    ]
