# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-31 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0008_auto_20180731_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorprofile',
            name='actions',
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='action',
            field=models.TextField(blank=True, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='monitorprofile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlists.WatchlistItem', verbose_name='Watchlist Item'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Parent'),
        ),
    ]
