# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_chart_template_name'),
        ('watchlists', '0009_auto_20180731_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorprofile',
            name='item',
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.AbstractProduct', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs.Type', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Watchlist'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Parent'),
        ),
    ]
