# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-01 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0006_month'),
        ('watchlists', '0010_auto_20180801_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorprofile',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='monitorprofile',
            name='color',
            field=models.CharField(choices=[('default', 'Default'), ('info', 'Info'), ('success', 'Success'), ('alert', 'Alert'), ('danger', 'Danger')], default='danger', max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='monitorprofile',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Watchlist'),
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='months',
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='months',
            field=models.ManyToManyField(to='configs.Month', verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Parent'),
        ),
    ]
