# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-29 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0006_month'),
        ('watchlists', '0014_auto_20180828_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorprofile',
            name='active',
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='monitorprofile',
            name='months',
            field=models.ManyToManyField(to='configs.Month', verbose_name='Monitor Months'),
        ),
        migrations.AlterField(
            model_name='monitorprofile',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Watchlist'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Parent'),
        ),
    ]
