# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-06 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0015_auto_20180829_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorprofile',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Watchlist'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlists.Watchlist', verbose_name='Parent'),
        ),
    ]
