# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrans', '0003_dailytran_not_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytran',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
    ]
