# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytrans', '0006_dailyreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'verbose_name': 'Daily Report', 'verbose_name_plural': 'Daily Reports'},
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
    ]
