# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-10-27 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0009_auto_20201027_0842'),
        ('dailytrans', '0007_auto_20191123_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=120, unique=True, verbose_name='File ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('festival_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.Festival', verbose_name='Festival ID')),
            ],
            options={
                'verbose_name': 'Festival Report',
                'verbose_name_plural': 'Festival Reports',
            },
        ),
    ]
