# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_auto_20180510_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproduct',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.Unit', verbose_name='Unit'),
        ),
    ]
