# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0006_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractproduct',
            options={'ordering': ('id',), 'verbose_name': 'Abstract Product', 'verbose_name_plural': 'Abstract Products'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('id',), 'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AddField(
            model_name='source',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs.Type', verbose_name='Type'),
        ),
    ]
