# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0007_auto_20180913_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
