# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-10-27 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0008_source_enable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roc_year', models.CharField(default=109, max_length=3, verbose_name='ROC Year')),
                ('enable', models.BooleanField(default=True, verbose_name='Enabled')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Festival',
                'verbose_name_plural': 'Festivals',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FestivalItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('enable', models.BooleanField(default=True, verbose_name='Enabled')),
                ('order_sn', models.IntegerField(default=9, verbose_name='Order SN')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'FestivalItem',
                'ordering': ('order_sn',),
            },
        ),
        migrations.CreateModel(
            name='FestivalName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('enable', models.BooleanField(default=True, verbose_name='Enabled')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'FestivalName',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='festivalitems',
            name='festivalname',
            field=models.ManyToManyField(to='configs.FestivalName', verbose_name='FestivalName'),
        ),
        migrations.AddField(
            model_name='festivalitems',
            name='product_id',
            field=models.ManyToManyField(to='configs.AbstractProduct', verbose_name='Product_id'),
        ),
        migrations.AddField(
            model_name='festivalitems',
            name='source',
            field=models.ManyToManyField(to='configs.Source', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='festival',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs.FestivalName', verbose_name='Name'),
        ),
    ]
