# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2023-01-05 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0011_last5yearsitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='roc_year',
            field=models.CharField(default=112, max_length=3, verbose_name='ROC Year'),
        ),
    ]
