# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 05:48
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181002_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='events:api:event_type_autocomplete', help_text='Enter a comma-separated tag string', initial='test, test2', space_delimiter=False, to='events.EventType', tree=True, verbose_name='Event Type', verbose_name_plural='Event Types'),
        ),
    ]
