# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 08:11
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181002_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='types',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='events:api:event_type_autocomplete', help_text='You can create new event type here', initial='test, test2', space_delimiter=False, to='events.EventType', tree=True, verbose_name='Event Type', verbose_name_plural='Event Types'),
        ),
    ]
