# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20181003_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='context',
            field=models.TextField(default='', verbose_name='Context'),
            preserve_default=False,
        ),
    ]
