# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-23 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='is_editor',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='event_editor',
            field=models.BooleanField(default=False, verbose_name='Event Editor'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='menu_viewer',
            field=models.BooleanField(default=False, verbose_name='Menu Item Viewer'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='watchlist_viewer',
            field=models.BooleanField(default=False, verbose_name='Watchlist Viewer'),
        ),
    ]
