# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-12 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181023_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='reporter',
            field=models.BooleanField(default=False, verbose_name='Reporter'),
        ),
    ]
