# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Event Type', 'verbose_name_plural': 'Event Types'},
        ),
        migrations.AlterUniqueTogether(
            name='eventtype',
            unique_together=set([]),
        ),
    ]
