# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181002_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='types',
        ),
    ]
