# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20181002_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ('level',), 'verbose_name': 'Event Type', 'verbose_name_plural': 'Event Types'},
        ),
        migrations.AddField(
            model_name='event',
            name='share',
            field=models.BooleanField(default=False, verbose_name='Shared Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='types',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='events:api:event_type_autocomplete', help_text='You can create new event type here', space_delimiter=False, to='events.EventType', tree=True, verbose_name='Event Type'),
        ),
    ]
