# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-11-17 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0011_last5yearsitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naifchickens',
            fields=[
                ('abstractproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='configs.AbstractProduct')),
            ],
            options={
                'verbose_name': 'Naifchickens',
                'verbose_name_plural': 'Naifchickens',
            },
            bases=('configs.abstractproduct',),
        ),
    ]
