# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-04-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_squashed_0004_auto_20181226_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='amislist_viewer',
            field=models.BooleanField(default=False, verbose_name='Amis List Viewer'),
        ),
    ]
