# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-10-27 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinformation_amislist_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='festivalreport_refresh',
            field=models.BooleanField(default=False, verbose_name='Festival Report Refresh'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='festivalreport_viewer',
            field=models.BooleanField(default=False, verbose_name='Festival Report Viewer'),
        ),
    ]
