# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-05-11 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201027_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='last5yearsreport_viewer',
            field=models.BooleanField(default=False, verbose_name='Last 5 Years Report Viewer'),
        ),
    ]
